services:
  api-cache:
    build: .
    container_name: gin-api-cache
    ports:
      - "8080:8080"
    mem_limit: 16g
    cpus: "16.0"
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=AppPass123!
      - DB_NAME=article_db
      - REDIS_ADDR=redis:6379
      # - REDIS_ADDR=""

  api-nocache:
    build: .
    container_name: gin-api-nocache
    ports:
      - "8081:8080"
    mem_limit: 16g
    cpus: "16.0"
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=AppPass123!
      - DB_NAME=article_db
      - REDIS_ADDR=""

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    mem_limit: 16g
    cpus: "16.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: article_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppPass123!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    mem_limit: 16g
    cpus: "16.0"
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
