sonar.projectKey=gin-app
sonar.projectName=gin-app
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.login=sqa_315b3224363446aedea338dd5ce58038e302d9f6

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/*.min.js
